# Generated by Django 5.1.5 on 2025-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_brand_image_path_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_path',
            field=models.ImageField(blank=True, default='', null=True, upload_to='brands'),
        ),
    ]
